# Generated by Django 4.0.6 on 2022-07-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tudolist',
            new_name='Todolist',
        ),
    ]
